Update deploy_setting.yml

diff --git a/.github/workflows/deploy_setting.yml b/.github/workflows/deploy_setting.yml
--- a/.github/workflows/deploy_setting.yml
+++ b/.github/workflows/deploy_setting.yml
@@ -98,13 +98,13 @@ jobs:
       run: |
         RAW_VERSION=$("$POWERPLATFORMTOOLS_PACPATH" --version)
         echo "Power Platform CLI raw version: $RAW_VERSION"
-        CLI_VERSION=$(echo "$RAW_VERSION" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
-        echo "Power Platform CLI parsed version: $CLI_VERSION"
-        REQUIRED_VERSION="1.10.4"
-        if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$CLI_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
-          echo "ERROR: Power Platform CLI version must be at least $REQUIRED_VERSION for JSON output support."
-          exit 1
-        fi
+     #   CLI_VERSION=$(echo "$RAW_VERSION" | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
+     #   echo "Power Platform CLI parsed version: $CLI_VERSION"
+     #   REQUIRED_VERSION="1.10.4"
+     #   if [ "$(printf '%s\n' "$REQUIRED_VERSION" "$CLI_VERSION" | sort -V | head -n1)" != "$REQUIRED_VERSION" ]; then
+     #     echo "ERROR: Power Platform CLI version must be at least $REQUIRED_VERSION for JSON output support."
+     #     exit 1
+     #   fi
 
     - name: Authenticate pac to TEST environment
       run: |
